import fs from "node:fs";
import path from "node:path";
import vm from "node:vm";

import { describe, expect, it } from "vitest";

const MODULE_PATH = path.resolve(process.cwd(), "js", "modules", "main-group-localization-services.js");

function loadMainGroupLocalizationServicesModule() {
    const code = fs.readFileSync(MODULE_PATH, "utf8");
    const sandbox = { window: {}, globalThis: {}, console };
    sandbox.globalThis = sandbox;
    vm.createContext(sandbox);
    vm.runInContext(code, sandbox, { filename: "js/modules/main-group-localization-services.js" });
    return sandbox.window.GTVMainGroupLocalizationServices
        || sandbox.GTVMainGroupLocalizationServices
        || sandbox.globalThis.GTVMainGroupLocalizationServices;
}

describe("GTV main group localization services module", () => {
    it("localizes auto-generated group and subgroup names", () => {
        const moduleApi = loadMainGroupLocalizationServicesModule();
        const groups = [{
            name: "Default Group 3",
            activeMultiSubgroupId: "subgroup-1",
            multiSubgroups: [{ id: "subgroup-1", name: "Subgroup 2" }]
        }];
        const service = moduleApi.createService({
            getGroups: () => groups,
            getCurrentGroup: () => groups[0],
            getMultiStateService: () => ({
                ensureGroupMultiSubgroups: () => { }
            }),
            t: (key) => {
                if (key === "default_group_name") return "Group";
                if (key === "default_subgroup_name") return "Sub";
                return key;
            }
        });

        const changed = service.localizeAutoGeneratedNamesForCurrentLanguage();

        expect(changed).toBe(true);
        expect(groups[0].name).toBe("Group 3");
        expect(groups[0].multiSubgroups[0].name).toBe("Sub 2");
        expect(service.parseAutoGeneratedIndexedName("Group 7", ["Group"])).toEqual({
            matched: true,
            number: 7
        });
    });

    it("syncs and loads current multi-state through active subgroup", () => {
        const moduleApi = loadMainGroupLocalizationServicesModule();
        const groups = [{
            activeMultiSubgroupId: "subgroup-0",
            multiSubgroups: [{
                id: "subgroup-0",
                name: "  ",
                multiRangeCount: 1,
                multiRanges: [],
                multiRangeCollapsed: [],
                multiRangeStartEditEnabled: [],
                multiRangeEndEditEnabled: []
            }]
        }];
        const runtimeState = {
            multiRangeCount: 2,
            multiRanges: [{ startUtcMs: NaN, endUtcMs: 20 }],
            multiRangeCollapsed: [1],
            multiRangeStartEditEnabled: [0],
            multiRangeEndEditEnabled: [1],
            multiRangeTitle: ""
        };
        let refreshCalls = 0;
        const multiStateService = {
            ensureGroupMultiSubgroups: () => { },
            sanitizeMultiSubgroupName: (value, fallback) => String(value || "").trim() || fallback,
            getDefaultMultiSubgroupName: () => "Subgroup 1",
            sanitizeMultiStatePayload: () => ({
                multiRangeCount: 3,
                multiRanges: [{ startUtcMs: 100, endUtcMs: 200 }],
                multiRangeCollapsed: [false],
                multiRangeStartEditEnabled: [true],
                multiRangeEndEditEnabled: [false]
            })
        };
        const service = moduleApi.createService({
            getGroups: () => groups,
            getCurrentGroup: () => groups[0],
            getMultiStateService: () => multiStateService,
            getMultiRangeState: () => runtimeState,
            setMultiRangeState: (next) => {
                Object.assign(runtimeState, next);
            },
            sanitizeMultiRangeCount: (value) => Number(value) || 1,
            sanitizeMultiRangeTitle: (value) => String(value || "").trim() || "subgroup",
            sanitizeUtcMs: (value, fallbackMs) => (Number.isFinite(value) ? value : fallbackMs),
            ensureMultiRangeState: () => { },
            refreshMultiRangeControls: () => { refreshCalls += 1; },
            now: () => 10
        });

        service.syncCurrentMultiStateToActiveSubgroup();
        const subgroup = groups[0].multiSubgroups[0];
        expect(subgroup.name).toBe("Subgroup 1");
        expect(subgroup.multiRangeCount).toBe(2);
        expect(subgroup.multiRanges[0]).toEqual({ startUtcMs: 10, endUtcMs: 20 });
        expect(subgroup.multiRangeCollapsed).toEqual([true]);
        expect(subgroup.multiRangeStartEditEnabled).toEqual([false]);

        service.loadCurrentMultiStateFromActiveSubgroup();
        expect(runtimeState.multiRangeCount).toBe(3);
        expect(runtimeState.multiRangeTitle).toBe("Subgroup 1");
        expect(refreshCalls).toBe(1);
    });
});
