import path from "node:path";
import { createRequire } from "node:module";

import { afterEach, describe, expect, it } from "vitest";

const MODULE_PATH = path.resolve(process.cwd(), "js", "modules", "main-persistence-services.js");
const require = createRequire(import.meta.url);
const MODULE_ID = require.resolve(MODULE_PATH);
const moduleCleanupStack = [];

function loadMainPersistenceServicesModule() {
    const globalPatches = { window: {}, console };
    const keys = ["window", "console", "GTVMainPersistenceServices", ...Object.keys(globalPatches)];
    const previous = new Map();
    keys.forEach((key) => {
        previous.set(key, {
            exists: Object.prototype.hasOwnProperty.call(globalThis, key),
            value: globalThis[key]
        });
    });

    Object.entries(globalPatches).forEach(([key, value]) => {
        globalThis[key] = value;
    });

    delete require.cache[MODULE_ID];
    require(MODULE_PATH);
    moduleCleanupStack.push(() => {
        delete require.cache[MODULE_ID];
        keys.forEach((key) => {
            const entry = previous.get(key);
            if (!entry || !entry.exists) {
                delete globalThis[key];
                return;
            }
            globalThis[key] = entry.value;
        });
    });

    return globalThis.window?.GTVMainPersistenceServices || globalThis.GTVMainPersistenceServices;
}

describe("GTV main persistence services module", () => {
    afterEach(() => {
        while (moduleCleanupStack.length) {
            const cleanup = moduleCleanupStack.pop();
            try {
                cleanup();
            } catch {
                // Ignore cleanup failures in tests.
            }
        }
    });
    it("creates persistence services through bundle factory with wired callbacks", () => {
        const moduleApi = loadMainPersistenceServicesModule();
        let config = null;
        let translationsCalled = 0;
        let subgroupCalled = 0;

        const services = moduleApi.createService({
            persistenceServiceBundleFactory: {
                createBundle: (cfg) => {
                    config = cfg;
                    return {
                        persistenceService: { id: "persistence" },
                        settingsIoService: { id: "settings-io" },
                        dataTransferService: { id: "data-transfer" },
                        uiSettingsActionsService: { id: "ui-settings-actions" }
                    };
                }
            },
            STORAGE_KEY: "s",
            THEME_STORAGE_KEY: "theme",
            LANG_STORAGE_KEY: "lang",
            UI_SCALE_STORAGE_KEY: "scale",
            LEGACY_STORAGE_KEYS: ["a"],
            LEGACY_STORAGE_FALLBACK_KEYS: ["b"],
            COPY_FORMAT_KEYS: ["timezone"],
            DEFAULT_TIME_ADJUST_DAY_STEP: 1,
            MIN_MULTI_RANGE_COUNT: 1,
            I18N_DATA: {},
            VERSION: "1.0.0",
            getDefaultFixedTimes: () => [],
            getDefaultFixedDate: () => "",
            getState: () => ({}),
            setState: () => {},
            getPersistenceSnapshot: () => ({}),
            ensureGroupMultiSubgroups: () => { subgroupCalled += 1; },
            sanitizeGroup: (g) => g,
            sanitizeBaseTimezoneId: (id) => id,
            sanitizeMainTab: (tab) => tab,
            sanitizeTimeAdjustDayStep: (v) => v,
            sanitizeCopyFormatOrder: (v) => v,
            sanitizeCopyFormatEnabled: (v) => v,
            sanitizeTimePartsEnabled: (v) => v,
            sanitizeFormatProfiles: (v) => v,
            deriveTimePartsFromLegacyEnabled: (v) => v,
            sanitizeMultiStatePayload: (v) => v,
            sanitizeMultiRangeTitle: (v) => v,
            loadCurrentMultiStateFromActiveSubgroup: () => {},
            ensureBaseTimezoneSelection: () => {},
            syncCurrentMultiStateToActiveSubgroup: () => {},
            loadThemePreference: () => "dark",
            applyTheme: () => {},
            loadUiScalePreference: () => 100,
            applyUiScale: () => {},
            populateUiScaleSelect: () => {},
            getCurrentUiScalePercent: () => 100,
            refreshMultiRangeControls: () => {},
            updateTZDropdown: () => {},
            refreshSelectWidths: () => {},
            switchMainTab: () => {},
            showToast: () => {},
            t: (key) => key,
            tFormat: (key) => key,
            applyVersionBranding: () => {},
            applyTranslations: () => { translationsCalled += 1; },
            getGroups: () => [],
            getCurrentTheme: () => "dark",
            getCurrentLang: () => "en",
            getCurrentMainTab: () => "live",
            sanitizeUtcRowOrder: (v) => v,
            sanitizeTheme: (v) => v,
            sanitizeUiScalePercent: (v) => v,
            setCurrentLang: () => {},
            loadPersistence: () => {},
            localizeAutoGeneratedNamesForCurrentLanguage: () => false,
            getActiveGroupId: () => 0,
            sanitizeFilenamePart: (v) => v,
            pad: (v) => String(v).padStart(2, "0"),
            renderGroups: () => {},
            renderMultiSubgroups: () => {},
            renderBaseTimeSelect: () => {},
            renderMultiRanges: () => {},
            renderList: () => {},
            isMultiTab: () => false,
            sanitizeMultiSubgroupId: (v) => v,
            sanitizeMultiSubgroupName: (v) => v,
            getDefaultMultiSubgroupName: () => "Subgroup 1",
            getCurrentMultiSubgroup: () => null,
            document: { getElementById: () => null }
        });

        expect(services.persistenceService.id).toBe("persistence");
        expect(services.settingsIoService.id).toBe("settings-io");
        expect(services.dataTransferService.id).toBe("data-transfer");
        expect(services.uiSettingsActionsService.id).toBe("ui-settings-actions");

        expect(config.STORAGE_KEY).toBe("s");
        expect(typeof config.applyTranslations).toBe("function");
        config.applyTranslations();
        expect(translationsCalled).toBe(1);
        config.ensureGroupMultiSubgroups({}, {});
        expect(subgroupCalled).toBe(1);
    });

    it("throws when bundle factory is missing", () => {
        const moduleApi = loadMainPersistenceServicesModule();
        expect(() => moduleApi.createService({})).toThrow("Missing required module API: persistenceServiceBundleFactory.createBundle");
    });
});
