import fs from "node:fs";
import path from "node:path";
import vm from "node:vm";

import { describe, expect, it } from "vitest";

const MODULE_PATH = path.resolve(process.cwd(), "js", "modules", "main-orchestration-flow-services.js");

function loadMainOrchestrationFlowServicesModule() {
    const code = fs.readFileSync(MODULE_PATH, "utf8");
    const sandbox = { window: {}, globalThis: {}, console };
    sandbox.globalThis = sandbox;
    vm.createContext(sandbox);
    vm.runInContext(code, sandbox, { filename: "js/modules/main-orchestration-flow-services.js" });
    return sandbox.window.GTVMainOrchestrationFlowServices
        || sandbox.GTVMainOrchestrationFlowServices
        || sandbox.globalThis.GTVMainOrchestrationFlowServices;
}

describe("GTV main orchestration flow services module", () => {
    it("proxies update/persistence/group-localization flows through composed services", () => {
        const moduleApi = loadMainOrchestrationFlowServicesModule();
        let updateCalls = 0;
        let snapshotCalls = 0;
        let syncCalls = 0;
        let loadCalls = 0;

        const service = moduleApi.createService({
            getMainClockOrchestratorService: () => ({
                updateClocks: () => { updateCalls += 1; }
            }),
            getMainPersistenceSnapshotService: () => ({
                getPersistenceSnapshot: () => {
                    snapshotCalls += 1;
                    return { key: "value" };
                }
            }),
            getMainGroupLocalizationService: () => ({
                parseAutoGeneratedIndexedName: () => ({ matched: true, number: 3 }),
                localizeAutoGeneratedNamesForCurrentLanguage: () => true,
                getCurrentMultiSubgroup: () => ({ id: "sg-1" }),
                getCurrentMultiSubgroupName: () => "Subgroup 1",
                syncCurrentMultiStateToActiveSubgroup: () => { syncCalls += 1; },
                loadCurrentMultiStateFromActiveSubgroup: () => { loadCalls += 1; }
            })
        });

        service.updateClocks();
        const snapshot = service.getPersistenceSnapshot();
        const parsed = service.parseAutoGeneratedIndexedName("Default Group 3", ["Default Group"]);
        const localized = service.localizeAutoGeneratedNamesForCurrentLanguage();
        const subgroup = service.getCurrentMultiSubgroup();
        const subgroupName = service.getCurrentMultiSubgroupName();
        service.syncCurrentMultiStateToActiveSubgroup();
        service.loadCurrentMultiStateFromActiveSubgroup();

        expect(updateCalls).toBe(1);
        expect(snapshotCalls).toBe(1);
        expect(snapshot).toEqual({ key: "value" });
        expect(parsed).toEqual({ matched: true, number: 3 });
        expect(localized).toBe(true);
        expect(subgroup).toEqual({ id: "sg-1" });
        expect(subgroupName).toBe("Subgroup 1");
        expect(syncCalls).toBe(1);
        expect(loadCalls).toBe(1);
    });

    it("returns safe fallbacks when composed services are missing", () => {
        const moduleApi = loadMainOrchestrationFlowServicesModule();
        const service = moduleApi.createService({
            warnMissingServiceMethod: () => {}
        });

        expect(service.getPersistenceSnapshot()).toEqual({});
        expect(service.parseAutoGeneratedIndexedName("x", ["Default Group"])).toEqual({ matched: false, number: null });
        expect(service.localizeAutoGeneratedNamesForCurrentLanguage()).toBe(false);
        expect(service.getCurrentMultiSubgroup()).toBe(null);
        expect(service.getCurrentMultiSubgroupName()).toBe("subgroup");
        expect(() => service.updateClocks()).not.toThrow();
        expect(() => service.syncCurrentMultiStateToActiveSubgroup()).not.toThrow();
        expect(() => service.loadCurrentMultiStateFromActiveSubgroup()).not.toThrow();
    });
});
