import fs from "node:fs";
import path from "node:path";
import vm from "node:vm";

import { describe, expect, it } from "vitest";

const MODULE_PATH = path.resolve(process.cwd(), "js", "modules", "main-app-bootstrap.js");

function loadMainAppBootstrapModule({ withWindow = true } = {}) {
    const code = fs.readFileSync(MODULE_PATH, "utf8");
    const sandbox = withWindow ? { window: {}, globalThis: {}, console } : { globalThis: {}, console };
    sandbox.globalThis = sandbox;
    vm.createContext(sandbox);
    vm.runInContext(code, sandbox, { filename: "js/modules/main-app-bootstrap.js" });
    return sandbox.window?.GTVMainAppBootstrap
        || sandbox.GTVMainAppBootstrap
        || sandbox.globalThis.GTVMainAppBootstrap;
}

describe("GTV main app bootstrap module", () => {
    it("runs initialization flow in stable order", async () => {
        const moduleApi = loadMainAppBootstrapModule();
        const order = [];
        const service = moduleApi.createService({
            assertRequiredServices: () => order.push("assert"),
            loadPersistence: async () => order.push("loadPersistence"),
            localizeAutoGeneratedNamesForCurrentLanguage: () => true,
            savePersistenceSafely: async () => order.push("savePersistence"),
            loadCurrentMultiStateFromActiveSubgroup: () => order.push("loadCurrentMultiState"),
            loadThemePreference: async () => "dark",
            applyTheme: async () => order.push("applyTheme"),
            loadUiScalePreference: async () => 100,
            applyUiScale: async () => order.push("applyUiScale"),
            applyTranslations: () => order.push("applyTranslations"),
            applyVersionBranding: () => order.push("applyVersionBranding"),
            initUI: () => order.push("initUI"),
            bindFloatingTooltipEvents: () => order.push("bindTooltip"),
            initDragAndDrop: () => order.push("dragdrop"),
            initSearchAndSelect: () => order.push("search"),
            initCalculators: () => order.push("calculator"),
            startRealtimeTicker: () => order.push("ticker"),
            switchMainTab: () => order.push("switchTab"),
            getCurrentMainTab: () => "live",
            updateClocks: () => order.push("updateClocks"),
            showFatalError: () => order.push("fatal")
        });

        await service.initApp();

        expect(order).toEqual([
            "assert",
            "loadPersistence",
            "savePersistence",
            "loadCurrentMultiState",
            "applyTheme",
            "applyUiScale",
            "applyTranslations",
            "applyVersionBranding",
            "initUI",
            "bindTooltip",
            "dragdrop",
            "search",
            "calculator",
            "ticker",
            "switchTab",
            "updateClocks"
        ]);
    });

    it("routes bootstrap errors to showFatalError", async () => {
        const moduleApi = loadMainAppBootstrapModule({ withWindow: false });
        const errors = [];
        const service = moduleApi.createService({
            assertRequiredServices: () => {
                throw new Error("boom");
            },
            showFatalError: (err) => errors.push(err.message)
        });

        await service.initApp();
        expect(errors).toEqual(["boom"]);
    });

    it("supports initApp with omitted dependencies", async () => {
        const moduleApi = loadMainAppBootstrapModule({ withWindow: false });
        const service = moduleApi.createService();

        await expect(service.initApp()).resolves.toBe(undefined);
    });
});
