import path from "node:path";
import { createRequire } from "node:module";

import { afterEach, describe, expect, it } from "vitest";

const MODULE_PATH = path.resolve(process.cwd(), "js", "modules", "main-orchestration-flow-services.js");
const require = createRequire(import.meta.url);
const MODULE_ID = require.resolve(MODULE_PATH);
const moduleCleanupStack = [];

function loadMainOrchestrationFlowServicesModule() {
    const globalPatches = { window: {}, console };
    const keys = ["window", "console", "GTVMainOrchestrationFlowServices", ...Object.keys(globalPatches)];
    const previous = new Map();
    keys.forEach((key) => {
        previous.set(key, {
            exists: Object.prototype.hasOwnProperty.call(globalThis, key),
            value: globalThis[key]
        });
    });

    Object.entries(globalPatches).forEach(([key, value]) => {
        globalThis[key] = value;
    });

    delete require.cache[MODULE_ID];
    require(MODULE_PATH);
    moduleCleanupStack.push(() => {
        delete require.cache[MODULE_ID];
        keys.forEach((key) => {
            const entry = previous.get(key);
            if (!entry || !entry.exists) {
                delete globalThis[key];
                return;
            }
            globalThis[key] = entry.value;
        });
    });

    return globalThis.window?.GTVMainOrchestrationFlowServices || globalThis.GTVMainOrchestrationFlowServices;
}

describe("GTV main orchestration flow services module", () => {
    afterEach(() => {
        while (moduleCleanupStack.length) {
            const cleanup = moduleCleanupStack.pop();
            try {
                cleanup();
            } catch {
                // Ignore cleanup failures in tests.
            }
        }
    });
    it("proxies update/persistence/group-localization flows through composed services", () => {
        const moduleApi = loadMainOrchestrationFlowServicesModule();
        let updateCalls = 0;
        let snapshotCalls = 0;
        let syncCalls = 0;
        let loadCalls = 0;

        const service = moduleApi.createService({
            getMainClockOrchestratorService: () => ({
                updateClocks: () => { updateCalls += 1; }
            }),
            getMainPersistenceSnapshotService: () => ({
                getPersistenceSnapshot: () => {
                    snapshotCalls += 1;
                    return { key: "value" };
                }
            }),
            getMainGroupLocalizationService: () => ({
                parseAutoGeneratedIndexedName: () => ({ matched: true, number: 3 }),
                localizeAutoGeneratedNamesForCurrentLanguage: () => true,
                getCurrentMultiSubgroup: () => ({ id: "sg-1" }),
                getCurrentMultiSubgroupName: () => "Subgroup 1",
                syncCurrentMultiStateToActiveSubgroup: () => { syncCalls += 1; },
                loadCurrentMultiStateFromActiveSubgroup: () => { loadCalls += 1; }
            })
        });

        service.updateClocks();
        const snapshot = service.getPersistenceSnapshot();
        const parsed = service.parseAutoGeneratedIndexedName("Default Group 3", ["Default Group"]);
        const localized = service.localizeAutoGeneratedNamesForCurrentLanguage();
        const subgroup = service.getCurrentMultiSubgroup();
        const subgroupName = service.getCurrentMultiSubgroupName();
        service.syncCurrentMultiStateToActiveSubgroup();
        service.loadCurrentMultiStateFromActiveSubgroup();

        expect(updateCalls).toBe(1);
        expect(snapshotCalls).toBe(1);
        expect(snapshot).toEqual({ key: "value" });
        expect(parsed).toEqual({ matched: true, number: 3 });
        expect(localized).toBe(true);
        expect(subgroup).toEqual({ id: "sg-1" });
        expect(subgroupName).toBe("Subgroup 1");
        expect(syncCalls).toBe(1);
        expect(loadCalls).toBe(1);
    });

    it("returns safe fallbacks when composed services are missing", () => {
        const moduleApi = loadMainOrchestrationFlowServicesModule();
        const service = moduleApi.createService({
            warnMissingServiceMethod: () => {}
        });

        expect(service.getPersistenceSnapshot()).toEqual({});
        expect(service.parseAutoGeneratedIndexedName("x", ["Default Group"])).toEqual({ matched: false, number: null });
        expect(service.localizeAutoGeneratedNamesForCurrentLanguage()).toBe(false);
        expect(service.getCurrentMultiSubgroup()).toBe(null);
        expect(service.getCurrentMultiSubgroupName()).toBe("subgroup");
        expect(() => service.updateClocks()).not.toThrow();
        expect(() => service.syncCurrentMultiStateToActiveSubgroup()).not.toThrow();
        expect(() => service.loadCurrentMultiStateFromActiveSubgroup()).not.toThrow();
    });

    it("uses injected consoleWarn fallback when warnMissingServiceMethod is not provided", () => {
        const moduleApi = loadMainOrchestrationFlowServicesModule();
        const warned = [];
        const service = moduleApi.createService({
            consoleWarn: (...args) => {
                warned.push(args);
            }
        });

        service.updateClocks();
        service.updateClocks();

        expect(warned).toHaveLength(1);
        expect(String(warned[0][0])).toContain("mainClockOrchestratorService.updateClocks");
    });
});
