import path from "node:path";
import { createRequire } from "node:module";

import { afterEach, describe, expect, it } from "vitest";

const MODULE_PATH = path.resolve(process.cwd(), "js", "modules", "main-app-bootstrap.js");
const require = createRequire(import.meta.url);
const MODULE_ID = require.resolve(MODULE_PATH);
const moduleCleanupStack = [];

function loadMainAppBootstrapModule({ withWindow = true } = {}) {
    const globalPatches = withWindow ? { window: {}, console } : { console };
    const keys = ["window", "console", "GTVMainAppBootstrap", ...Object.keys(globalPatches)];
    const previous = new Map();
    keys.forEach((key) => {
        previous.set(key, {
            exists: Object.prototype.hasOwnProperty.call(globalThis, key),
            value: globalThis[key]
        });
    });

    Object.entries(globalPatches).forEach(([key, value]) => {
        globalThis[key] = value;
    });

    delete require.cache[MODULE_ID];
    require(MODULE_PATH);
    moduleCleanupStack.push(() => {
        delete require.cache[MODULE_ID];
        keys.forEach((key) => {
            const entry = previous.get(key);
            if (!entry || !entry.exists) {
                delete globalThis[key];
                return;
            }
            globalThis[key] = entry.value;
        });
    });

    return globalThis.window?.GTVMainAppBootstrap
        || globalThis.GTVMainAppBootstrap;
}

describe("GTV main app bootstrap module", () => {
    afterEach(() => {
        while (moduleCleanupStack.length) {
            const cleanup = moduleCleanupStack.pop();
            try {
                cleanup();
            } catch {
                // Ignore cleanup failures in tests.
            }
        }
    });

    it("runs initialization flow in stable order", async () => {
        const moduleApi = loadMainAppBootstrapModule();
        const order = [];
        const service = moduleApi.createService({
            assertRequiredServices: () => order.push("assert"),
            loadPersistence: async () => order.push("loadPersistence"),
            localizeAutoGeneratedNamesForCurrentLanguage: () => true,
            savePersistenceSafely: async () => order.push("savePersistence"),
            loadCurrentMultiStateFromActiveSubgroup: () => order.push("loadCurrentMultiState"),
            loadThemePreference: async () => "dark",
            applyTheme: async () => order.push("applyTheme"),
            loadUiScalePreference: async () => 100,
            applyUiScale: async () => order.push("applyUiScale"),
            applyTranslations: () => order.push("applyTranslations"),
            applyVersionBranding: () => order.push("applyVersionBranding"),
            initUI: () => order.push("initUI"),
            bindFloatingTooltipEvents: () => order.push("bindTooltip"),
            initDragAndDrop: () => order.push("dragdrop"),
            initSearchAndSelect: () => order.push("search"),
            initCalculators: () => order.push("calculator"),
            startRealtimeTicker: () => order.push("ticker"),
            switchMainTab: () => order.push("switchTab"),
            getCurrentMainTab: () => "live",
            updateClocks: () => order.push("updateClocks"),
            showFatalError: () => order.push("fatal")
        });

        await service.initApp();

        expect(order).toEqual([
            "assert",
            "loadPersistence",
            "savePersistence",
            "loadCurrentMultiState",
            "applyTheme",
            "applyUiScale",
            "applyTranslations",
            "applyVersionBranding",
            "initUI",
            "bindTooltip",
            "dragdrop",
            "search",
            "calculator",
            "ticker",
            "switchTab",
            "updateClocks"
        ]);
    });

    it("routes bootstrap errors to showFatalError", async () => {
        const moduleApi = loadMainAppBootstrapModule({ withWindow: false });
        const errors = [];
        const service = moduleApi.createService({
            assertRequiredServices: () => {
                throw new Error("boom");
            },
            showFatalError: (err) => errors.push(err.message)
        });

        await service.initApp();
        expect(errors).toEqual(["boom"]);
    });

    it("supports initApp with omitted dependencies", async () => {
        const moduleApi = loadMainAppBootstrapModule({ withWindow: false });
        const service = moduleApi.createService();

        await expect(service.initApp()).resolves.toBe(undefined);
    });

    it("routes async persistence load errors to showFatalError (simulating corrupted storage)", async () => {
        const moduleApi = loadMainAppBootstrapModule({ withWindow: false });
        const errors = [];
        const service = moduleApi.createService({
            assertRequiredServices: () => {},
            loadPersistence: async () => {
                throw new Error("Corrupted local storage JSON");
            },
            showFatalError: (err) => errors.push(err.message)
        });

        await service.initApp();
        expect(errors).toEqual(["Corrupted local storage JSON"]);
    });
});
