import path from "node:path";
import { createRequire } from "node:module";

import { afterEach, describe, expect, it } from "vitest";

const MODULE_PATH = path.resolve(process.cwd(), "js", "modules", "settings-io.js");
const require = createRequire(import.meta.url);
const MODULE_ID = require.resolve(MODULE_PATH);
const moduleCleanupStack = [];

function loadSettingsIoModule(options = {}) {
    const logs = {
        error: [],
        warn: [],
        log: []
    };
    const consoleStub = {
        error(...args) {
            logs.error.push(args);
        },
        warn(...args) {
            logs.warn.push(args);
        },
        log(...args) {
            logs.log.push(args);
        }
    };
    const documentStub = options.document || {
        getElementById() {
            return null;
        }
    };
    const globalPatches = {
        window: {},
        document: documentStub,
        console: consoleStub,
        ...options.globals
    };
    const keys = [
        "window",
        "document",
        "console",
        "GTVSettingsIO",
        ...Object.keys(globalPatches)
    ];
    const previous = new Map();
    keys.forEach((key) => {
        previous.set(key, {
            exists: Object.prototype.hasOwnProperty.call(globalThis, key),
            value: globalThis[key]
        });
    });

    Object.entries(globalPatches).forEach(([key, value]) => {
        globalThis[key] = value;
    });

    delete require.cache[MODULE_ID];
    require(MODULE_PATH);
    moduleCleanupStack.push(() => {
        delete require.cache[MODULE_ID];
        keys.forEach((key) => {
            const entry = previous.get(key);
            if (!entry || !entry.exists) {
                delete globalThis[key];
                return;
            }
            globalThis[key] = entry.value;
        });
    });

    return {
        module: globalThis.window?.GTVSettingsIO || globalThis.GTVSettingsIO,
        logs
    };
}

function createBaseDeps(overrides = {}) {
    const groups = [
        {
            name: "Group A",
            zones: [],
            baseTimezoneId: "utc",
            showUtcRow: true,
            utcRowOrder: 0
        }
    ];
    let currentLang = "ko";
    let currentTheme = "dark";
    return {
        I18N_DATA: { ko: {}, en: {} },
        THEME_STORAGE_KEY: "THEME_KEY",
        LANG_STORAGE_KEY: "LANG_KEY",
        UI_SCALE_STORAGE_KEY: "SCALE_KEY",
        getGroups: () => groups,
        sanitizeBaseTimezoneId: (value) => (value === "utc" ? "utc" : String(value || "")),
        sanitizeUtcRowOrder: (value) => (Number.isFinite(Number(value)) ? Number(value) : 0),
        sanitizeMainTab: (tab) => (["live", "fixed", "multi", "fixed-time", "calc"].includes(tab) ? tab : "live"),
        sanitizeGroup: (group, idx) => ({
            name: String(group?.name || `Group ${idx + 1}`),
            zones: Array.isArray(group?.zones) ? group.zones : [],
            baseTimezoneId: "utc",
            showUtcRow: true,
            utcRowOrder: 0
        }),
        sanitizeMultiStatePayload: () => null,
        sanitizeMultiRangeTitle: (value) => String(value || ""),
        getDefaultFixedDate: () => "",
        getDefaultFixedTimes: () => [],
        persistStorageSnapshot: async () => ({ ok: true, error: null }),
        setStorageValue: async () => ({ ok: true, error: null }),
        sanitizeTheme: (theme) => String(theme || "dark"),
        sanitizeUiScalePercent: (value) => {
            const parsed = Number(value);
            return Number.isFinite(parsed) ? parsed : 100;
        },
        getStorageValue: async (_key, fallback) => fallback,
        setCurrentLang: (lang) => {
            currentLang = lang;
        },
        loadPersistence: async () => { },
        localizeAutoGeneratedNamesForCurrentLanguage: () => false,
        savePersistence: async () => true,
        loadThemePreference: async () => "dark",
        applyTheme: async (theme) => {
            currentTheme = theme;
        },
        loadUiScalePreference: async () => 100,
        applyUiScale: async () => { },
        applyTranslations: () => { },
        applyVersionBranding: () => { },
        getCurrentLang: () => currentLang,
        getCurrentTheme: () => currentTheme,
        populateUiScaleSelect: () => { },
        getCurrentUiScalePercent: () => 100,
        refreshMultiRangeControls: () => { },
        updateTZDropdown: () => { },
        refreshSelectWidths: () => { },
        switchMainTab: () => { },
        getCurrentMainTab: () => "live",
        ...overrides
    };
}

describe("GTV settings IO module", () => {
    afterEach(() => {
        while (moduleCleanupStack.length) {
            const cleanup = moduleCleanupStack.pop();
            try {
                cleanup();
            } catch {
                // Ignore cleanup failures in tests.
            }
        }
    });

    it("throws for invalid payload without groups array", async () => {
        const loaded = loadSettingsIoModule();
        const service = loaded.module.createService(createBaseDeps());

        await expect(service.applyImportedSettings({ data: {} })).rejects.toThrow("groups is required");
    });

    it("throws for invalid settings payload when payload is not an object", async () => {
        const loaded = loadSettingsIoModule();
        const service = loaded.module.createService(createBaseDeps());

        await expect(service.applyImportedSettings(null)).rejects.toThrow("Invalid settings payload");
    });

    it("throws PERSISTENCE_WRITE_FAILED when root snapshot persist fails", async () => {
        const loaded = loadSettingsIoModule();
        const cause = new Error("persist failed");
        const service = loaded.module.createService(createBaseDeps({
            persistStorageSnapshot: async () => ({ ok: false, error: cause })
        }));

        await expect(service.applyImportedSettings({ data: { groups: [] } })).rejects.toMatchObject({
            code: "PERSISTENCE_WRITE_FAILED",
            cause
        });
    });

    it("throws PERSISTENCE_WRITE_FAILED when preference persist fails", async () => {
        const loaded = loadSettingsIoModule();
        const cause = new Error("pref write failed");
        const service = loaded.module.createService(createBaseDeps({
            setStorageValue: async (key) => {
                if (key === "THEME_KEY") return { ok: false, error: cause };
                return { ok: true, error: null };
            }
        }));

        await expect(service.applyImportedSettings({
            data: { groups: [] },
            preferences: { theme: "light" }
        })).rejects.toMatchObject({
            code: "PERSISTENCE_WRITE_FAILED",
            cause
        });
    });

    it("throws PERSISTENCE_WRITE_FAILED when preference write result is missing", async () => {
        const loaded = loadSettingsIoModule();
        const service = loaded.module.createService(createBaseDeps({
            setStorageValue: async () => null
        }));

        await expect(service.applyImportedSettings({
            data: { groups: [] },
            preferences: { theme: "light" }
        })).rejects.toMatchObject({
            code: "PERSISTENCE_WRITE_FAILED",
            cause: null
        });
    });

    it("handles non-array groups from getGroups without crashing", async () => {
        const loaded = loadSettingsIoModule();
        const service = loaded.module.createService(createBaseDeps({
            getGroups: () => null
        }));

        await expect(service.applyImportedSettings({ data: { groups: [] } })).resolves.toBeUndefined();
    });

    it("normalizes empty-zone group fallback and persists once", async () => {
        const loaded = loadSettingsIoModule();
        const groups = [
            {
                name: "Group A",
                zones: [],
                baseTimezoneId: "tz-1",
                showUtcRow: false,
                utcRowOrder: 3
            }
        ];
        let saveCount = 0;
        const service = loaded.module.createService(createBaseDeps({
            getGroups: () => groups,
            sanitizeBaseTimezoneId: (value) => (value === "utc" ? "utc" : "tz"),
            sanitizeUtcRowOrder: (value) => Number(value),
            savePersistence: async () => {
                saveCount += 1;
                return true;
            }
        }));

        await service.applyImportedSettings({ data: { groups: [] } });

        expect(groups[0].baseTimezoneId).toBe("utc");
        expect(groups[0].showUtcRow).toBe(true);
        expect(groups[0].utcRowOrder).toBe(0);
        expect(saveCount).toBe(1);
    });

    it("throws PERSISTENCE_WRITE_FAILED when localization-triggered save fails", async () => {
        const loaded = loadSettingsIoModule();
        const service = loaded.module.createService(createBaseDeps({
            localizeAutoGeneratedNamesForCurrentLanguage: () => true,
            savePersistence: async () => false
        }));

        await expect(service.applyImportedSettings({ data: { groups: [] } })).rejects.toMatchObject({
            code: "PERSISTENCE_WRITE_FAILED"
        });
    });

    it("throws PERSISTENCE_WRITE_FAILED when standard-time fallback save fails", async () => {
        const loaded = loadSettingsIoModule();
        const groups = [
            {
                name: "Needs Fallback",
                zones: [],
                baseTimezoneId: "bad-zone",
                showUtcRow: false,
                utcRowOrder: 2
            }
        ];
        const service = loaded.module.createService(createBaseDeps({
            getGroups: () => groups,
            sanitizeBaseTimezoneId: (value) => String(value || ""),
            sanitizeUtcRowOrder: (value) => Number(value),
            savePersistence: async () => false
        }));

        await expect(service.applyImportedSettings({ data: { groups: [] } })).rejects.toMatchObject({
            code: "PERSISTENCE_WRITE_FAILED"
        });
    });

    it("sanitizes import payload before persistence write", async () => {
        const loaded = loadSettingsIoModule();
        let persisted = null;
        const service = loaded.module.createService(createBaseDeps({
            sanitizeGroup: (_group, idx) => ({
                name: `Sanitized ${idx + 1}`,
                zones: [],
                baseTimezoneId: "utc",
                showUtcRow: true,
                utcRowOrder: 0
            }),
            persistStorageSnapshot: async (snapshot) => {
                persisted = snapshot;
                return { ok: true, error: null };
            }
        }));

        await service.applyImportedSettings({
            data: {
                groups: [{ name: "Raw Group", zones: [{ id: "bad", zone: "Invalid/Zone" }] }],
                activeGroupId: 99,
                currentMainTab: "broken-tab",
                activeGroupIdByMainTab: { live: 99, fixed: -5 },
                slotCount: 99,
                showCopyFormat: 1,
                showTimeline: "yes"
            }
        });

        expect(persisted).not.toBeNull();
        expect(Array.isArray(persisted.groups)).toBe(true);
        expect(persisted.groups[0].name).toBe("Sanitized 1");
        expect(persisted.activeGroupId).toBe(0);
        expect(persisted.currentMainTab).toBe("live");
        expect(persisted.activeGroupIdByMainTab.live).toBe(0);
        expect(persisted.activeGroupIdByMainTab.fixed).toBe(0);
        expect(persisted.slotCount).toBe(2);
        expect(persisted.showCopyFormat).toBe(true);
        expect(persisted.showTimeline).toBe(true);
        expect(persisted.dayStartHour).toBe(6);
        expect(persisted.nightStartHour).toBe(18);
    });

    it("keeps sanitized base timezone when active group contains matching zone id", async () => {
        const loaded = loadSettingsIoModule();
        let persisted = null;
        const service = loaded.module.createService(createBaseDeps({
            sanitizeGroup: () => ({
                name: "Group A",
                zones: [{ id: "zone-1" }],
                baseTimezoneId: "utc",
                showUtcRow: true,
                utcRowOrder: 0
            }),
            sanitizeBaseTimezoneId: (value) => String(value || ""),
            persistStorageSnapshot: async (snapshot) => {
                persisted = snapshot;
                return { ok: true, error: null };
            }
        }));

        await service.applyImportedSettings({
            data: {
                groups: [{ name: "Raw Group" }],
                baseTimezoneId: "zone-1"
            }
        });

        expect(persisted.baseTimezoneId).toBe("zone-1");
    });

    it("uses custom normalized payload when normalizeImportedPayload returns object", async () => {
        const loaded = loadSettingsIoModule();
        const customPayload = {
            groups: [{ name: "From custom", zones: [] }],
            activeGroupId: 0
        };
        let persisted = null;
        const service = loaded.module.createService(createBaseDeps({
            normalizeImportedPayload: () => customPayload,
            sanitizeGroup: () => {
                throw new Error("sanitizeGroup should not be called when normalizeImportedPayload succeeds");
            },
            persistStorageSnapshot: async (snapshot) => {
                persisted = snapshot;
                return { ok: true, error: null };
            }
        }));

        await service.applyImportedSettings({ data: { groups: [{ name: "Ignored raw value" }] } });

        expect(persisted).toBe(customPayload);
    });

    it("falls back to local sanitization when normalizeImportedPayload throws", async () => {
        const loaded = loadSettingsIoModule();
        let persisted = null;
        const service = loaded.module.createService(createBaseDeps({
            normalizeImportedPayload: () => {
                throw new Error("normalize error");
            },
            persistStorageSnapshot: async (snapshot) => {
                persisted = snapshot;
                return { ok: true, error: null };
            }
        }));

        await service.applyImportedSettings({
            data: {
                groups: [{ name: "Raw Group" }],
                currentMainTab: "broken"
            }
        });

        expect(persisted.currentMainTab).toBe("live");
        expect(loaded.logs.warn.length).toBe(1);
        expect(String(loaded.logs.warn[0][0])).toContain("normalizeImportedPayload failed");
    });

    it("clones raw groups when sanitizeGroup dependency is unavailable", async () => {
        const loaded = loadSettingsIoModule();
        const sourceGroup = {
            name: "Raw Group",
            zones: [{ id: "zone-a", zone: "Etc/UTC" }],
            customField: "preserved"
        };
        let persisted = null;
        const service = loaded.module.createService(createBaseDeps({
            sanitizeGroup: undefined,
            persistStorageSnapshot: async (snapshot) => {
                persisted = snapshot;
                return { ok: true, error: null };
            }
        }));

        await service.applyImportedSettings({ data: { groups: [sourceGroup] } });

        expect(persisted.groups[0]).toEqual(sourceGroup);
        expect(persisted.groups[0]).not.toBe(sourceGroup);
    });

    it("creates default fallback group when sanitizeGroup is unavailable and input groups are empty", async () => {
        const loaded = loadSettingsIoModule();
        let persisted = null;
        const service = loaded.module.createService(createBaseDeps({
            sanitizeGroup: undefined,
            t: () => "   ",
            getDefaultFixedDate: undefined,
            getDefaultFixedTimes: undefined,
            persistStorageSnapshot: async (snapshot) => {
                persisted = snapshot;
                return { ok: true, error: null };
            }
        }));

        await service.applyImportedSettings({ data: { groups: [] } });

        expect(Array.isArray(persisted.groups)).toBe(true);
        expect(persisted.groups.length).toBe(1);
        expect(persisted.groups[0].name).toBe("Group");
        expect(persisted.groups[0].fixedDate).toBe("");
        expect(persisted.groups[0].fixedTimes).toEqual([]);
    });

    it("passes legacy global multi-range state into fallback sanitizeGroup path", async () => {
        const loaded = loadSettingsIoModule();
        let persisted = null;
        let callIndex = 0;
        const service = loaded.module.createService(createBaseDeps({
            sanitizeMultiStatePayload: (state) => ({ ...state }),
            sanitizeMultiRangeTitle: (value) => `title:${value}`,
            sanitizeGroup: (_group, _idx, legacyState) => {
                callIndex += 1;
                if (callIndex === 1) return null;
                return {
                    name: "Sanitized Fallback",
                    zones: [],
                    baseTimezoneId: "utc",
                    showUtcRow: true,
                    utcRowOrder: 0,
                    legacyState
                };
            },
            persistStorageSnapshot: async (snapshot) => {
                persisted = snapshot;
                return { ok: true, error: null };
            }
        }));

        await service.applyImportedSettings({
            data: {
                groups: [{ name: "Raw Group" }],
                multiRangeCount: 2,
                multiRangeTitle: "custom-title",
                multiRanges: [{ id: "r1" }]
            }
        });

        expect(persisted.groups[0].name).toBe("Sanitized Fallback");
        expect(persisted.groups[0].legacyState.multiRangeCount).toBe(2);
        expect(persisted.groups[0].legacyState.multiRangeTitle).toBe("title:custom-title");
    });

    it("uses local main-tab sanitizer when sanitizeMainTab dependency is unavailable", async () => {
        const loaded = loadSettingsIoModule();
        const persisted = [];
        const service = loaded.module.createService(createBaseDeps({
            sanitizeMainTab: undefined,
            persistStorageSnapshot: async (snapshot) => {
                persisted.push(snapshot);
                return { ok: true, error: null };
            }
        }));

        await service.applyImportedSettings({ data: { groups: [{ name: "A" }], currentMainTab: "calc" } });
        await service.applyImportedSettings({ data: { groups: [{ name: "A" }], currentMainTab: "invalid-tab" } });

        expect(persisted[0].currentMainTab).toBe("calc");
        expect(persisted[1].currentMainTab).toBe("live");
    });

    it("updates UI controls and runs post-import hooks with sanitized preferences", async () => {
        const langSelect = { value: "" };
        const themeSelect = { value: "" };
        const uiScaleSelect = { value: "" };
        const documentStub = {
            getElementById(id) {
                return {
                    "lang-select": langSelect,
                    "theme-select": themeSelect,
                    "ui-scale-select": uiScaleSelect
                }[id] || null;
            }
        };
        const loaded = loadSettingsIoModule({ document: documentStub });
        const setStorageCalls = [];
        let populatedUiScale = null;
        let refreshMultiRangeControlsCount = 0;
        let updateTZDropdownCount = 0;
        let refreshSelectWidthsCount = 0;
        const switchedTabs = [];
        const service = loaded.module.createService(createBaseDeps({
            setStorageValue: async (key, value, options) => {
                setStorageCalls.push({ key, value, options });
                return { ok: true, error: null };
            },
            sanitizeTheme: (theme) => `sanitized-${theme}`,
            sanitizeUiScalePercent: () => 135,
            getStorageValue: async () => "en",
            loadThemePreference: async () => "light",
            loadUiScalePreference: async () => 125,
            getCurrentUiScalePercent: () => 125,
            populateUiScaleSelect: (element) => {
                populatedUiScale = element;
            },
            refreshMultiRangeControls: () => {
                refreshMultiRangeControlsCount += 1;
            },
            updateTZDropdown: () => {
                updateTZDropdownCount += 1;
            },
            refreshSelectWidths: () => {
                refreshSelectWidthsCount += 1;
            },
            switchMainTab: (tab) => {
                switchedTabs.push(tab);
            },
            getCurrentMainTab: () => "fixed"
        }));

        await service.applyImportedSettings({
            data: { groups: [] },
            preferences: { theme: "light", language: "en", uiScale: 200 }
        });

        expect(setStorageCalls).toEqual([
            { key: "THEME_KEY", value: "sanitized-light", options: { suppressToast: true } },
            { key: "LANG_KEY", value: "en", options: { suppressToast: true } },
            { key: "SCALE_KEY", value: "135", options: { suppressToast: true } }
        ]);
        expect(langSelect.value).toBe("en");
        expect(themeSelect.value).toBe("light");
        expect(populatedUiScale).toBe(uiScaleSelect);
        expect(uiScaleSelect.value).toBe("125");
        expect(refreshMultiRangeControlsCount).toBe(1);
        expect(updateTZDropdownCount).toBe(1);
        expect(refreshSelectWidthsCount).toBe(1);
        expect(switchedTabs).toEqual(["fixed"]);
    });

    it("treats root object as both payload and preference source", async () => {
        const loaded = loadSettingsIoModule();
        const setStorageCalls = [];
        const service = loaded.module.createService(createBaseDeps({
            setStorageValue: async (key, value) => {
                setStorageCalls.push({ key, value });
                return { ok: true, error: null };
            },
            getStorageValue: async () => "en"
        }));

        await service.applyImportedSettings({
            groups: [],
            theme: "dark",
            language: "en",
            uiScale: 110
        });

        expect(setStorageCalls).toEqual([
            { key: "THEME_KEY", value: "dark" },
            { key: "LANG_KEY", value: "en" },
            { key: "SCALE_KEY", value: "110" }
        ]);
    });
});
