import fs from "node:fs";
import path from "node:path";
import vm from "node:vm";

import { describe, expect, it } from "vitest";

const MODULE_PATH = path.resolve(process.cwd(), "js", "modules", "settings-io.js");

function loadSettingsIoModule() {
    const code = fs.readFileSync(MODULE_PATH, "utf8");
    const logs = {
        error: [],
        warn: [],
        log: []
    };
    const consoleStub = {
        error(...args) {
            logs.error.push(args);
        },
        warn(...args) {
            logs.warn.push(args);
        },
        log(...args) {
            logs.log.push(args);
        }
    };
    const sandbox = {
        window: {},
        globalThis: {},
        document: {
            getElementById() {
                return null;
            }
        },
        console: consoleStub
    };
    sandbox.globalThis = sandbox;
    vm.createContext(sandbox);
    vm.runInContext(code, sandbox, { filename: "js/modules/settings-io.js" });
    return {
        module: sandbox.window.GTVSettingsIO || sandbox.GTVSettingsIO || sandbox.globalThis.GTVSettingsIO,
        logs
    };
}

function createBaseDeps(overrides = {}) {
    const groups = [
        {
            name: "Group A",
            zones: [],
            baseTimezoneId: "utc",
            showUtcRow: true,
            utcRowOrder: 0
        }
    ];
    let currentLang = "ko";
    let currentTheme = "dark";
    return {
        I18N_DATA: { ko: {}, en: {} },
        THEME_STORAGE_KEY: "THEME_KEY",
        LANG_STORAGE_KEY: "LANG_KEY",
        UI_SCALE_STORAGE_KEY: "SCALE_KEY",
        getGroups: () => groups,
        sanitizeBaseTimezoneId: (value) => (value === "utc" ? "utc" : String(value || "")),
        sanitizeUtcRowOrder: (value) => (Number.isFinite(Number(value)) ? Number(value) : 0),
        sanitizeMainTab: (tab) => (["live", "fixed", "multi", "fixed-time", "calc"].includes(tab) ? tab : "live"),
        sanitizeGroup: (group, idx) => ({
            name: String(group?.name || `Group ${idx + 1}`),
            zones: Array.isArray(group?.zones) ? group.zones : [],
            baseTimezoneId: "utc",
            showUtcRow: true,
            utcRowOrder: 0
        }),
        sanitizeMultiStatePayload: () => null,
        sanitizeMultiRangeTitle: (value) => String(value || ""),
        getDefaultFixedTimes: () => [],
        persistStorageSnapshot: async () => ({ ok: true, error: null }),
        setStorageValue: async () => ({ ok: true, error: null }),
        sanitizeTheme: (theme) => String(theme || "dark"),
        sanitizeUiScalePercent: (value) => {
            const parsed = Number(value);
            return Number.isFinite(parsed) ? parsed : 100;
        },
        getStorageValue: async (_key, fallback) => fallback,
        setCurrentLang: (lang) => {
            currentLang = lang;
        },
        loadPersistence: async () => { },
        localizeAutoGeneratedNamesForCurrentLanguage: () => false,
        savePersistence: async () => true,
        loadThemePreference: async () => "dark",
        applyTheme: async (theme) => {
            currentTheme = theme;
        },
        loadUiScalePreference: async () => 100,
        applyUiScale: async () => { },
        applyTranslations: () => { },
        applyVersionBranding: () => { },
        getCurrentLang: () => currentLang,
        getCurrentTheme: () => currentTheme,
        populateUiScaleSelect: () => { },
        getCurrentUiScalePercent: () => 100,
        refreshMultiRangeControls: () => { },
        updateTZDropdown: () => { },
        refreshSelectWidths: () => { },
        switchMainTab: () => { },
        getCurrentMainTab: () => "live",
        ...overrides
    };
}

describe("GTV settings IO module", () => {
    it("throws for invalid payload without groups array", async () => {
        const loaded = loadSettingsIoModule();
        const service = loaded.module.createService(createBaseDeps());

        await expect(service.applyImportedSettings({ data: {} })).rejects.toThrow("groups is required");
    });

    it("throws PERSISTENCE_WRITE_FAILED when root snapshot persist fails", async () => {
        const loaded = loadSettingsIoModule();
        const cause = new Error("persist failed");
        const service = loaded.module.createService(createBaseDeps({
            persistStorageSnapshot: async () => ({ ok: false, error: cause })
        }));

        await expect(service.applyImportedSettings({ data: { groups: [] } })).rejects.toMatchObject({
            code: "PERSISTENCE_WRITE_FAILED",
            cause
        });
    });

    it("throws PERSISTENCE_WRITE_FAILED when preference persist fails", async () => {
        const loaded = loadSettingsIoModule();
        const cause = new Error("pref write failed");
        const service = loaded.module.createService(createBaseDeps({
            setStorageValue: async (key) => {
                if (key === "THEME_KEY") return { ok: false, error: cause };
                return { ok: true, error: null };
            }
        }));

        await expect(service.applyImportedSettings({
            data: { groups: [] },
            preferences: { theme: "light" }
        })).rejects.toMatchObject({
            code: "PERSISTENCE_WRITE_FAILED",
            cause
        });
    });

    it("handles non-array groups from getGroups without crashing", async () => {
        const loaded = loadSettingsIoModule();
        const service = loaded.module.createService(createBaseDeps({
            getGroups: () => null
        }));

        await expect(service.applyImportedSettings({ data: { groups: [] } })).resolves.toBeUndefined();
    });

    it("normalizes empty-zone group fallback and persists once", async () => {
        const loaded = loadSettingsIoModule();
        const groups = [
            {
                name: "Group A",
                zones: [],
                baseTimezoneId: "tz-1",
                showUtcRow: false,
                utcRowOrder: 3
            }
        ];
        let saveCount = 0;
        const service = loaded.module.createService(createBaseDeps({
            getGroups: () => groups,
            sanitizeBaseTimezoneId: (value) => (value === "utc" ? "utc" : "tz"),
            sanitizeUtcRowOrder: (value) => Number(value),
            savePersistence: async () => {
                saveCount += 1;
                return true;
            }
        }));

        await service.applyImportedSettings({ data: { groups: [] } });

        expect(groups[0].baseTimezoneId).toBe("utc");
        expect(groups[0].showUtcRow).toBe(true);
        expect(groups[0].utcRowOrder).toBe(0);
        expect(saveCount).toBe(1);
    });

    it("sanitizes import payload before persistence write", async () => {
        const loaded = loadSettingsIoModule();
        let persisted = null;
        const service = loaded.module.createService(createBaseDeps({
            sanitizeGroup: (_group, idx) => ({
                name: `Sanitized ${idx + 1}`,
                zones: [],
                baseTimezoneId: "utc",
                showUtcRow: true,
                utcRowOrder: 0
            }),
            persistStorageSnapshot: async (snapshot) => {
                persisted = snapshot;
                return { ok: true, error: null };
            }
        }));

        await service.applyImportedSettings({
            data: {
                groups: [{ name: "Raw Group", zones: [{ id: "bad", zone: "Invalid/Zone" }] }],
                activeGroupId: 99,
                currentMainTab: "broken-tab",
                activeGroupIdByMainTab: { live: 99, fixed: -5 },
                slotCount: 99,
                showCopyFormat: 1,
                showTimeline: "yes"
            }
        });

        expect(persisted).not.toBeNull();
        expect(Array.isArray(persisted.groups)).toBe(true);
        expect(persisted.groups[0].name).toBe("Sanitized 1");
        expect(persisted.activeGroupId).toBe(0);
        expect(persisted.currentMainTab).toBe("live");
        expect(persisted.activeGroupIdByMainTab.live).toBe(0);
        expect(persisted.activeGroupIdByMainTab.fixed).toBe(0);
        expect(persisted.slotCount).toBe(2);
        expect(persisted.showCopyFormat).toBe(true);
        expect(persisted.showTimeline).toBe(true);
    });
});
