(function initGtvMainUiInit(globalObj) {
    "use strict";

    function createService(deps = {}) {
        const t = deps.t || ((key) => key);
        const switchMainTab = deps.switchMainTab;
        const populateUiScaleSelect = deps.populateUiScaleSelect;
        const getUiScale = deps.getUiScale;
        const applyUiScale = deps.applyUiScale;
        const getMultiRangeCount = deps.getMultiRangeCount;
        const setMultiRangeCount = deps.setMultiRangeCount;
        const refreshMultiRangeControls = deps.refreshMultiRangeControls;
        const getFixedTimeSlotCountForCurrentGroup = deps.getFixedTimeSlotCountForCurrentGroup;
        const setFixedTimeSlotCount = deps.setFixedTimeSlotCount;
        const refreshFixedTimeSlotCountControls = deps.refreshFixedTimeSlotCountControls;
        const bindCustomDatePickerForInput = deps.bindCustomDatePickerForInput;
        const getCurrentGroup = deps.getCurrentGroup;
        const ensureGroupFixedTimes = deps.ensureGroupFixedTimes;
        const setCurrentGroupFixedDate = deps.setCurrentGroupFixedDate;
        const sanitizeFixedDateValue = deps.sanitizeFixedDateValue;
        const showToast = deps.showToast;
        const normalizeCustomAbbr = deps.normalizeCustomAbbr;
        const addTimezone = deps.addTimezone;
        const createUniqueTimezoneId = deps.createUniqueTimezoneId;
        const syncActiveFormatProfileFromState = deps.syncActiveFormatProfileFromState;
        const getSlotCount = deps.getSlotCount;
        const setSlotCount = deps.setSlotCount;
        const activateFormatProfileForCurrentContext = deps.activateFormatProfileForCurrentContext;
        const renderList = deps.renderList;
        const renderCopyFormatControls = deps.renderCopyFormatControls;
        const updateCopyFormatPreview = deps.updateCopyFormatPreview;
        const savePersistence = deps.savePersistence;
        const getShowCopyFormat = deps.getShowCopyFormat;
        const setShowCopyFormat = deps.setShowCopyFormat;
        const getShowTimeline = deps.getShowTimeline;
        const setShowTimeline = deps.setShowTimeline;
        const renderTimelineFrame = deps.renderTimelineFrame;
        const resetDisplayFormatForActiveContext = deps.resetDisplayFormatForActiveContext;
        const resetCopyFormatForActiveContext = deps.resetCopyFormatForActiveContext;
        const applyCurrentGroupBaseTimezoneId = deps.applyCurrentGroupBaseTimezoneId;
        const addGroup = deps.addGroup;
        const addMultiSubgroup = deps.addMultiSubgroup;
        const copyAllTimezones = deps.copyAllTimezones;
        const saveTimezoneTableImage = deps.saveTimezoneTableImage;
        const saveMultiRangeTitlesImage = deps.saveMultiRangeTitlesImage;
        const bindTransferControls = deps.bindTransferControls;
        const getCurrentTheme = deps.getCurrentTheme;
        const applyTheme = deps.applyTheme;
        const refreshCalculator = deps.refreshCalculator;
        const getCurrentLang = deps.getCurrentLang;
        const hideFloatingTooltip = deps.hideFloatingTooltip;
        const setLanguage = deps.setLanguage;
        const localizeAutoGeneratedNamesForCurrentLanguage = deps.localizeAutoGeneratedNamesForCurrentLanguage;
        const applyVersionBranding = deps.applyVersionBranding;
        const updateTZDropdown = deps.updateTZDropdown;
        const renderGroups = deps.renderGroups;
        const renderMultiSubgroups = deps.renderMultiSubgroups;
        const updateTimeAdjustPanel = deps.updateTimeAdjustPanel;
        const refreshSelectWidths = deps.refreshSelectWidths;
        const bindResetControls = deps.bindResetControls;
        const renderBaseTimeSelect = deps.renderBaseTimeSelect;
        const updateOptionRowVisibility = deps.updateOptionRowVisibility;
        const upgradeNativeTitleTooltips = deps.upgradeNativeTitleTooltips;

        function initUI() {
            // 메인 탭
            document.querySelectorAll(".nav-item").forEach((btn) => {
                btn.addEventListener("click", () => switchMainTab(btn.dataset.tab));
            });

            const uiScaleSelect = document.getElementById("ui-scale-select");
            if (uiScaleSelect) {
                populateUiScaleSelect(uiScaleSelect);
                uiScaleSelect.value = String(Math.round(getUiScale() * 100));
                uiScaleSelect.addEventListener("change", (e) => {
                    applyUiScale(e.target.value);
                    uiScaleSelect.value = String(Math.round(getUiScale() * 100));
                });
            }

            const multiRangeCountInput = document.getElementById("multi-range-count-input");
            const multiRangeDecreaseBtn = document.getElementById("multi-range-count-decrease");
            const multiRangeIncreaseBtn = document.getElementById("multi-range-count-increase");
            if (multiRangeCountInput) {
                const commitRangeCount = () => {
                    setMultiRangeCount(multiRangeCountInput.value, { persist: true, rerender: true, showBoundaryToast: true });
                };
                multiRangeCountInput.addEventListener("input", () => {
                    multiRangeCountInput.value = String(multiRangeCountInput.value || "").replace(/[^0-9]/g, "");
                });
                multiRangeCountInput.addEventListener("change", commitRangeCount);
                multiRangeCountInput.addEventListener("blur", commitRangeCount);
                multiRangeCountInput.addEventListener("keydown", (e) => {
                    if (e.key !== "Enter") return;
                    commitRangeCount();
                    multiRangeCountInput.blur();
                });
            }
            if (multiRangeDecreaseBtn) {
                multiRangeDecreaseBtn.addEventListener("click", () => {
                    setMultiRangeCount(getMultiRangeCount() - 1, { persist: true, rerender: true, showBoundaryToast: true });
                });
            }
            if (multiRangeIncreaseBtn) {
                multiRangeIncreaseBtn.addEventListener("click", () => {
                    setMultiRangeCount(getMultiRangeCount() + 1, { persist: true, rerender: true, showBoundaryToast: true });
                });
            }

            refreshMultiRangeControls();
            const fixedTimeSlotCountInput = document.getElementById("fixed-time-slot-count-input");
            const fixedTimeSlotDecreaseBtn = document.getElementById("fixed-time-slot-count-decrease");
            const fixedTimeSlotIncreaseBtn = document.getElementById("fixed-time-slot-count-increase");
            const fixedTimeDateInput = document.getElementById("fixed-time-date-input");
            const fixedTimeDateTrigger = document.getElementById("fixed-time-date-trigger");
            if (fixedTimeSlotCountInput) {
                const commitFixedTimeSlotCount = () => {
                    setFixedTimeSlotCount(fixedTimeSlotCountInput.value, { persist: true, rerender: true, showBoundaryToast: true });
                };
                fixedTimeSlotCountInput.addEventListener("input", () => {
                    fixedTimeSlotCountInput.value = String(fixedTimeSlotCountInput.value || "").replace(/[^0-9]/g, "");
                });
                fixedTimeSlotCountInput.addEventListener("change", commitFixedTimeSlotCount);
                fixedTimeSlotCountInput.addEventListener("blur", commitFixedTimeSlotCount);
                fixedTimeSlotCountInput.addEventListener("keydown", (e) => {
                    if (e.key !== "Enter") return;
                    commitFixedTimeSlotCount();
                    fixedTimeSlotCountInput.blur();
                });
            }
            if (fixedTimeSlotDecreaseBtn) {
                fixedTimeSlotDecreaseBtn.addEventListener("click", () => {
                    const nextCount = getFixedTimeSlotCountForCurrentGroup() - 1;
                    setFixedTimeSlotCount(nextCount, { persist: true, rerender: true, showBoundaryToast: true });
                });
            }
            if (fixedTimeSlotIncreaseBtn) {
                fixedTimeSlotIncreaseBtn.addEventListener("click", () => {
                    const nextCount = getFixedTimeSlotCountForCurrentGroup() + 1;
                    setFixedTimeSlotCount(nextCount, { persist: true, rerender: true, showBoundaryToast: true });
                });
            }
            if (fixedTimeDateInput && fixedTimeDateTrigger) {
                bindCustomDatePickerForInput(fixedTimeDateInput, fixedTimeDateTrigger, { preserveValue: true, type: "date" });
            }
            if (fixedTimeDateInput) {
                const commitFixedDate = () => {
                    const group = getCurrentGroup();
                    if (!group) return;
                    ensureGroupFixedTimes(group);
                    const before = group.fixedDate || "";
                    const rawInput = String(fixedTimeDateInput.value || "").trim();
                    if (!rawInput) {
                        setCurrentGroupFixedDate("", { persist: true, rerender: true });
                        fixedTimeDateInput.value = "";
                        return;
                    }
                    const normalized = sanitizeFixedDateValue(rawInput, "");
                    if (!normalized) {
                        showToast(t("toast_invalid_date"));
                        fixedTimeDateInput.value = before;
                        return;
                    }
                    const changed = setCurrentGroupFixedDate(normalized, { persist: true, rerender: true });
                    fixedTimeDateInput.value = changed ? normalized : (getCurrentGroup()?.fixedDate || normalized);
                };
                fixedTimeDateInput.addEventListener("input", () => {
                    fixedTimeDateInput.value = String(fixedTimeDateInput.value || "").replace(/[^0-9-]/g, "").slice(0, 10);
                });
                fixedTimeDateInput.addEventListener("change", commitFixedDate);
                fixedTimeDateInput.addEventListener("blur", commitFixedDate);
                fixedTimeDateInput.addEventListener("keydown", (e) => {
                    if (e.key !== "Enter") return;
                    commitFixedDate();
                    fixedTimeDateInput.blur();
                });
            }
            refreshFixedTimeSlotCountControls();

            // 커스텀 오프셋 시간 선택 옵션 채우기
            const hSel = document.getElementById("custom-off-h");
            if (hSel) {
                for (let i = 14; i >= -12; i--) {
                    const o = document.createElement("option");
                    o.value = i;
                    const sign = i > 0 ? "+" : (i < 0 ? "-" : "+");
                    o.textContent = `${sign}${String(Math.abs(i)).padStart(2, "0")}`;
                    if (i === 0) o.selected = true;
                    hSel.appendChild(o);
                }
            }

            // 추가 시간 토글
            const extraTimeToggle = document.getElementById("toggle-extra-time");
            if (extraTimeToggle) {
                extraTimeToggle.checked = getSlotCount() > 1;
                extraTimeToggle.addEventListener("change", (e) => {
                    syncActiveFormatProfileFromState();
                    setSlotCount(e.target.checked ? 2 : 1);
                    activateFormatProfileForCurrentContext({ syncCurrent: false });
                    renderList();
                    renderCopyFormatControls();
                    updateCopyFormatPreview();
                    savePersistence();
                });
            }

            const copyFormatToggle = document.getElementById("toggle-copy-format");
            if (copyFormatToggle) {
                copyFormatToggle.checked = getShowCopyFormat();
                copyFormatToggle.addEventListener("change", (e) => {
                    setShowCopyFormat(!!e.target.checked);
                    renderCopyFormatControls();
                    savePersistence();
                });
            }
            const timelineToggle = document.getElementById("toggle-timeline");
            if (timelineToggle) {
                timelineToggle.checked = getShowTimeline();
                timelineToggle.addEventListener("change", (e) => {
                    setShowTimeline(!!e.target.checked);
                    renderTimelineFrame();
                    savePersistence();
                });
            }

            const displayFormatResetBtn = document.getElementById("display-format-reset-btn");
            if (displayFormatResetBtn) {
                displayFormatResetBtn.addEventListener("click", () => {
                    resetDisplayFormatForActiveContext();
                    renderCopyFormatControls();
                    renderList();
                    savePersistence();
                });
            }

            const copyFormatResetBtn = document.getElementById("copy-format-reset-btn");
            if (copyFormatResetBtn) {
                copyFormatResetBtn.addEventListener("click", () => {
                    resetCopyFormatForActiveContext();
                    renderCopyFormatControls();
                    savePersistence();
                });
            }

            const baseTimeSelect = document.getElementById("base-time-select");
            if (baseTimeSelect) {
                baseTimeSelect.addEventListener("change", (e) => {
                    applyCurrentGroupBaseTimezoneId(e.target.value || "utc", { persist: true });
                });
            }

            // 커스텀 시간대
            const addCustomBtn = document.getElementById("add-custom-btn");
            if (addCustomBtn) {
                addCustomBtn.addEventListener("click", () => {
                    const abbrInput = document.getElementById("custom-abbr");
                    const nameInput = document.getElementById("custom-name");
                    const offHInput = document.getElementById("custom-off-h");
                    const offMInput = document.getElementById("custom-off-m");
                    const abbr = normalizeCustomAbbr(abbrInput?.value);
                    const name = (nameInput?.value || "").trim();
                    const offH = parseInt(offHInput?.value, 10) || 0;
                    const offM = parseInt(offMInput?.value, 10) || 0;
                    if (!name) return showToast(t("toast_input_name"));
                    const added = addTimezone({ id: createUniqueTimezoneId("tz-c"), abbr, name, offH, offM, type: "custom" });
                    if (added === false) return;
                    if (abbrInput) abbrInput.value = "";
                    if (nameInput) nameInput.value = "";
                });
            }

            const addGroupBtn = document.getElementById("add-group-btn");
            if (addGroupBtn) {
                addGroupBtn.addEventListener("click", () => {
                    addGroup();
                });
            }
            const addMultiSubgroupBtn = document.getElementById("add-multi-subgroup-btn");
            if (addMultiSubgroupBtn) {
                addMultiSubgroupBtn.addEventListener("click", () => {
                    addMultiSubgroup();
                });
            }

            const copyAllBtn = document.getElementById("copy-all-btn");
            if (copyAllBtn) {
                copyAllBtn.addEventListener("click", copyAllTimezones);
            }
            const saveTableImageBtn = document.getElementById("save-table-image-btn");
            if (saveTableImageBtn) {
                saveTableImageBtn.addEventListener("click", () => {
                    saveTimezoneTableImage();
                });
            }
            const saveMultiRangeTitlesImageBtn = document.getElementById("save-multi-range-titles-image-btn");
            if (saveMultiRangeTitlesImageBtn) {
                saveMultiRangeTitlesImageBtn.addEventListener("click", () => {
                    saveMultiRangeTitlesImage();
                });
            }
            bindTransferControls();

            const themeSelect = document.getElementById("theme-select");
            if (themeSelect) {
                themeSelect.value = getCurrentTheme();
                themeSelect.addEventListener("change", async (e) => {
                    await applyTheme(e.target.value);
                    refreshCalculator();
                });
            }

            // 언어 선택기
            const langSelect = document.getElementById("lang-select");
            if (langSelect) {
                langSelect.value = getCurrentLang();
                langSelect.addEventListener("change", (e) => {
                    hideFloatingTooltip();
                    setLanguage(e.target.value);
                    if (localizeAutoGeneratedNamesForCurrentLanguage()) {
                        savePersistence();
                    }
                    applyVersionBranding();
                    updateTZDropdown();
                    renderGroups();
                    renderMultiSubgroups();
                    renderList();
                    updateTimeAdjustPanel();
                    renderCopyFormatControls();
                    refreshSelectWidths();
                    refreshCalculator();
                });
            }

            bindResetControls();

            document.querySelectorAll(".info-tip").forEach((tip) => {
                tip.addEventListener("click", (e) => {
                    e.preventDefault();
                    e.stopPropagation();
                });
            });

            renderBaseTimeSelect();
            refreshSelectWidths();
            updateOptionRowVisibility();
            updateTimeAdjustPanel();
            renderCopyFormatControls();
            renderTimelineFrame();
            upgradeNativeTitleTooltips(document);
        }

        return Object.freeze({
            initUI
        });
    }

    globalObj.GTVMainUiInit = Object.freeze({
        createService
    });
})(typeof window !== "undefined" ? window : globalThis);
