(function initGtvSettingsIo(globalObj) {
    "use strict";

    function createService(deps) {
        function ensureImportedGroupsFallbackToStandardTime() {
            let changed = false;
            const groups = deps.getGroups();
            groups.forEach((group) => {
                if (!group || typeof group !== "object") return;
                const zoneCount = Array.isArray(group.zones) ? group.zones.length : 0;
                if (zoneCount > 0) return;

                if (deps.sanitizeBaseTimezoneId(group.baseTimezoneId) !== "utc") {
                    group.baseTimezoneId = "utc";
                    changed = true;
                }
                if (group.showUtcRow === false) {
                    group.showUtcRow = true;
                    changed = true;
                }
                if (deps.sanitizeUtcRowOrder(group.utcRowOrder) !== 0) {
                    group.utcRowOrder = 0;
                    changed = true;
                }
            });
            return changed;
        }

        async function applyImportedSettings(importedRoot) {
            const payload = (importedRoot && typeof importedRoot === "object" && importedRoot.data && typeof importedRoot.data === "object")
                ? importedRoot.data
                : importedRoot;
            if (!payload || typeof payload !== "object") {
                throw new Error("Invalid settings payload");
            }
            if (!Array.isArray(payload.groups)) {
                throw new Error("Invalid settings payload: groups is required");
            }

            const writeResult = await deps.persistStorageSnapshot(payload, { suppressToast: true });
            if (!writeResult.ok) {
                const persistErr = new Error("Failed to persist imported settings payload");
                persistErr.code = "PERSISTENCE_WRITE_FAILED";
                persistErr.cause = writeResult.error;
                throw persistErr;
            }

            const pref = (importedRoot && typeof importedRoot === "object" && importedRoot.preferences && typeof importedRoot.preferences === "object")
                ? importedRoot.preferences
                : importedRoot;

            if (pref && typeof pref === "object") {
                if (typeof pref.theme === "string") {
                    await deps.setStorageValue(deps.THEME_STORAGE_KEY, deps.sanitizeTheme(pref.theme), { suppressToast: true });
                }
                if (typeof pref.language === "string" && deps.I18N_DATA[pref.language]) {
                    await deps.setStorageValue(deps.LANG_STORAGE_KEY, pref.language, { suppressToast: true });
                }
                if (pref.uiScale !== undefined) {
                    await deps.setStorageValue(deps.UI_SCALE_STORAGE_KEY, String(deps.sanitizeUiScalePercent(pref.uiScale)), { suppressToast: true });
                }
            }

            const nextLang = localStorage.getItem(deps.LANG_STORAGE_KEY) || "ko";
            deps.setCurrentLang(deps.I18N_DATA[nextLang] ? nextLang : "ko");
            await deps.loadPersistence();
            if (deps.localizeAutoGeneratedNamesForCurrentLanguage()) {
                await deps.savePersistence();
            }
            if (ensureImportedGroupsFallbackToStandardTime()) {
                await deps.savePersistence();
            }
            await deps.applyTheme(await deps.loadThemePreference(), false);
            await deps.applyUiScale(await deps.loadUiScalePreference(), false);
            deps.applyTranslations();
            deps.applyVersionBranding();

            const langSelect = document.getElementById("lang-select");
            if (langSelect) langSelect.value = deps.getCurrentLang();

            const themeSelect = document.getElementById("theme-select");
            if (themeSelect) themeSelect.value = deps.getCurrentTheme();
            const uiScaleSelect = document.getElementById("ui-scale-select");
            if (uiScaleSelect) {
                deps.populateUiScaleSelect(uiScaleSelect);
                uiScaleSelect.value = String(deps.getCurrentUiScalePercent());
            }
            deps.refreshMultiRangeControls();

            deps.updateTZDropdown();
            deps.refreshSelectWidths();
            deps.switchMainTab(deps.getCurrentMainTab());
        }

        return Object.freeze({
            applyImportedSettings
        });
    }

    globalObj.GTVSettingsIO = Object.freeze({
        createService
    });
})(typeof window !== "undefined" ? window : globalThis);
